### ISSUE TITLE
SQL injection 

### ISSUE THREAD

**Issue by Outworldz** [justincc/opensimulator-helper#1]
SQL injection looks possible via XMLRPC   

$query = "select UserID from Presence where UserID='".$agentid."' and SecureSessionID = '".$sessionid."'";

A sessionid of a ";drop database opensim; would not be a good thing to send to this script.

**Comment by justinccdev** [comment]
This isn't an injection because of line 49

```
$sessionid = mysql_escape_string($s_session_id);
```

**Comment by Outworldz** [comment]
Good point. However, mysql_escape_string is deprecated since PHP 4.3, and removed entirely in PHP 7.0.
http://php.net/manual/en/function.mysql-escape-string.php

Thank you very much for answering.  Do you still consult for $Paypal on Opensim code? I am not interested in developing to put in core.  I do need a interesting mod to a particular function.  It's a Good Thing and will help hundreds to thousands of people. It is easy to understand what needs to be done. It is beyond my capabilities in C++ and Opensim.  A  very good opensim dev says it is doable.  If interested,  please email me at fred@outworldz.com and I'll send details.  I have a nice budget for this and am not in a hurry.   

Hope you are doing well

Fred

**Comment by justinccdev** [comment]
Thanks Fred.  Unfortunately, I no longer work on OpenSimulator or virtual worlds, so will not be updating this code for the new PHP MySQL modules. If someone needs this I'm afraid they will need to fork this repository and do the work themselves.

Hope you are well too.

**Comment by Outworldz** [comment]
Thanks for all the good work you did.
